### ISSUE TITLE
debug keyword

### ISSUE THREAD

**Issue by frsechet** [CSML-by-Clevy/csml-engine#183]
**Is your feature request related to a problem? Please describe.**
a debug action verb that's equivalent to say Debug() would be more straightforward

**Describe the solution you'd like**
```
debug x => say Debug(x)
debug x, y, z => say Debug(x, y, z)
```

**Comment by amerelo** [comment]
debug x, y, z is a bit weird maybe just debug(x, y, z) ?

**Comment by frsechet** [comment]
in this context, `debug` is an action verb, same as `say`, `do`, `remember`... So not a function with `(params)`. And besides, the goal is to avoid `say Debug(x, y, z)`

The main goal I guess is to be able to have a `key(string) / value(any)` for simple/naive debugging:

```
do someValue = someComplexStuff(a, b, c)
debug "here1" someValue
```

But I agree that this is inconsistent with how action verbs usually work in CSML.

**Comment by amerelo** [comment]
I agree that debug is not a function but the lack of delimitation of the arguments can be problematic if for example the user put a trailing comma like this

```
debug x, 
say "test"
```
the only possible error message that i can return  is 'say is a protected keyword and can not be use as variable' 
and that can be hard to understand for the user
