### ISSUE TITLE
Validate user input for number or float

### ISSUE THREAD

**Issue by AamirNakhwa** [CSML-by-Clevy/csml-engine#238]
I reviewed the documentation and it's not mentioned anywhere to validate the user input as a valid number or float.

**Comment by amerelo** [comment]
Hello AamirNakhwa,

the event is a complex type that can be hard to understand, if it can help you can see it as a string and you can check the if the user input (event) is a int/float or both by calling the method event.is_int() / event.is_float() / event.is_number() 

https://docs.csml.dev/language/the-event
https://docs.csml.dev/language/standard-library/string-methods#is_number-is_int-is_float

**Comment by frsechet** [comment]
To expand on what @amerelo says:

```
// event: 42.123
do is_number = event.is_number() // true
do is_int = event.is_int() // false
do is_float = event.is_float() // true

// event: 24
do is_number = event.is_number() // true
do is_int = event.is_int() // true
do is_float = event.is_float() // false

// event: "somestring"
do is_number = event.is_number() // false
do is_int = event.is_int() // false
do is_float = event.is_float() // false

```
