### ISSUE TITLE
Cannot send/receive audio with Chatwoot integration ( Whatsapp channel)

### ISSUE THREAD

**Issue by abdulaziz-mohammed** [CSML-by-Clevy/csml-engine#430]
**Describe the bug**
Cannot send or receive audio with Chatwoot integration through Whatsapp channel

**To Reproduce**
followed the instructions on how to setup Chatwoot integration then added a whatsapp channel, everything else works tho.

**Expected behavior**
Should  send and receive audio from customer and agent

**Comment by frsechet** [comment]
This is not a CSML Engine bug but a feature request for CSML Studio. Closing.

**Comment by abdulaziz-mohammed** [comment]
It's a deal breaker for me as customers tend to start with their issue in recorded audio format, everything about the aspect of Chatwoot/Whatsapp integration is great tho.

**Comment by frsechet** [comment]
I understand, but this request has nothing to do with this repo. Please use www.csml.dev/slack for CSML Studio feature requests.
