### ISSUE TITLE
npm is missing in the dockerfile

### ISSUE THREAD

**Issue by Jeffrey-H** [CSML-by-Clevy/csml-engine#432]
**Describe the bug**
npm is missing in the dockerfile

**To Reproduce**
Pull the docker image and start it.

**Expected behavior**
A running docker container

**Additional context**
Output that npm is missing:
```
ERROR: for csml-engine  Cannot start service csml-engine: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "npm": executable file not found in $PATH: unknown
```

**Comment by frsechet** [comment]
Why should it have npm? I don't understand.

**Comment by Jeffrey-H** [comment]
Nevermind, I came across a broken link of the docker-compose.yml on https://hub.docker.com/r/clevy/csml-engine and thought the blob was moved from the csml-engine-docker repository, and it is. But it's a really old version.

In that old docker-compose.yml file there is a command: "npm run start". Could you please recreate the docker-compose.yml blob file?

**Comment by frsechet** [comment]
This was indeed a very old version from when CSML only came as a rust binding. Now it comes as a complete web server written in (also fully written in rust). You don't need to "npm run start". Just run this container as explained in the docs and query its API to interact with it.

Docs: https://hub.docker.com/r/clevy/csml-engine
API: https://github.com/CSML-by-Clevy/csml-engine/blob/dev/csml_server/swagger.yaml
