### ISSUE TITLE
Telegram chatbot buttons are not displayed in a list

### ISSUE THREAD

**Issue by FleaFlist** [CSML-by-Clevy/csml-engine#439]
**Describe the bug**
Hi

I'm not quite sure if it's a bug or not, but for some reason in the Telegram chatbot connected to CSML Studio chatbot only displays buttons horizontally, and because of that long button captions don't fit if there are more than 2 buttons.

**To Reproduce**
My code:
![image](https://github.com/CSML-by-Clevy/docs-studio/assets/148443088/07c8fcdc-05f6-45b0-827e-ad97bbb4d085)

Telegram chatbot dialog looks like:
![image](https://github.com/CSML-by-Clevy/docs-studio/assets/148443088/81611a6e-be8a-4b79-9924-20890890b05f)

**Expected behavior**
Buttons should be displayed in the dialog with Telegram chatbot in the form of a list

**Additional context**
In the preview window of the editor buttons displays correct.
![image](https://github.com/CSML-by-Clevy/csml-engine/assets/148443088/c8622d6a-c95d-4994-89fe-19129eb2c94e)

How do I make the buttons in Telegram display as a vertical list?

**Comment by frsechet** [comment]
This is the CSML engine codebase which has nothing to do with telegram, so I'm closing this ticket. For CSML studio-related issues, please join the community slack https://csml.dev/slack.

(as an aside, the answer to your question is that it is not supported nor planned for the time being)
