### ISSUE TITLE
improve `match` behavior for multiple options

### ISSUE THREAD

**Issue by frsechet** [CSML-by-Clevy/csml-engine#64]
The current behavior of the match keyword works for single options but makes it hard to find _what_ the input matches if there are several options. For instance:

```
say Question(
  "What do you like best?", 
  buttons=[
    Button("Pizza") as pizza,
    Button("Salad") as salad,
    Button("Cheese") as cheese
  ]
)
hold
if (event match pizza) goto ValidChoice
else if (event match salad) goto ValidChoice
else if (event match pizza) goto ValidChoice
else goto NotValid
```

A better option would be to be able to find **if** the user selected an option, like for instance:

```
if (event.match_any(pizza, salad, cheese)) goto ValidChoice
else goto NotValid
```

We could further improve this behavior by having it return the actual item that matches:

```
do found = event.match_any(pizza, salad, cheese)
if (found) say "Found: {{found.title}}"
else say "Not found"
```

**Comment by amerelo** [comment]
how about a generic .match(...args) that would be an improvement/drop-in replacement on the current match keyword, that just returns the first matched item, or Null?
