### ISSUE TITLE
Debug component

### ISSUE THREAD

**Issue by frsechet** [CSML-by-Clevy/csml-engine#65]
To print any value, you currently need to `say "{{value}}"`, which can not be differentiated from a legit `say` instruction and shows a non-pretty-printed value.

A `Debug()` component would be able to take any value as a parameter, format it properly and wrap it unchanged in a dedicated component that could be left unimplemented by the consuming channel, allowing the developers to leave debug calls that could only appear on the channel when in "debug" mode.

**Comment by amerelo** [comment]
The 'Debug()' component can be Debug(x, y, z) => { content_type: "debug", content: { args: [x, y, z] }

**Comment by frsechet** [comment]
Makes sense, then each channel can implement a way to inspect args on `say Debug(some_val, otherval, 42, "plop")`
