### ISSUE TITLE
event.to_int() crashes if event is not a numerical value

### ISSUE THREAD

**Issue by frsechet** [CSML-by-Clevy/csml-engine#67]
If we need to force-cast a value to an int, we are expected to use the method `val.to_int()`. However, if `val = "string"`, this operation throws an exception.

```
do x = "string".to_int()
```

### Expected behavior:

x = 0 or x = Null

**Comment by amerelo** [comment]
this was fix at the same time as #57, this fix prevent the interpreter from stopping on error an instead it sends an error component and continues with Null as the default value
